### ISSUE TITLE
Improve actionHandler

### ISSUE THREAD

**Issue by yongpingchen** [KiiPlatform/thing-if-ThingSDK#128]
Currently, actionHandler return true|false, then sdk will update action result based on the return value. 
For some action like OTA, the action result need to be updated out of application scope, sdk should not update this kind of action result. 

Improve action handler by
- leave action results update out of sdk
- provide commandID as parameter

**Comment by satoshikumano** [comment]
Decided to use `KII_THING_IF_CUSTOM_PUSH_HANDLER` in those cases.
