### ISSUE TITLE
SDK can not recover network connection after getting 'fail to get host'

### ISSUE THREAD

**Issue by dairyo** [KiiPlatform/thing-if-ThingSDK#58]
@kiiCarlos said:

```
@thing-if SDK engineers - on the Client SDK I’m getting ‘failed to get host’ 
when the internet hiccups. Then the SDK doesn’t recover 
when the internet comes back.  Any tips on what method I can look at 
so I can get it to self-recover or reset the connection?
```

Please confirm.

**Comment by dairyo** [comment]
@kiiCarlos 

I checked connection recovering behavior but I could not find a problem which you said. Network connection was automatically recovered.

In below section, I describe how to check the behavior.

### Environment
- OS: mac OS El capitan
- Used SDK Version: 458b3e3e74510358cc8cc8ef1b51b60ea39f64a7

### Test procedure
1. Move to linux-sample directory
   
   ``` sh
   cd linux-sample
   ```
2. Build test application
   
   ``` sh
   make DEBUG=1 KEEP_ALIVE_INTERVAL=10
   ```
   
   `DEBUG=1` is set to show SDK log.
   `KEEP_ALIVE_INTERVAL=10` is set to shorten keep alive interval. Default value is 300. It means 300 seconds. By this, it is changed to 10 second.
3. Execute the test application
   
   ``` sh
   ./exampleapp onboard --vendor-thing-id=test-vendor --password=pass
   ```
   
   After that, you can find following log. The log indicates test application successfully executing.
   
   ``` sh
   file:../kii/kii/kii_push.c, line:338 readPointer: 1566747936
   ```
4. Disconnect network connection
   
   To disconnect network connection, I turned off Wi-Fi connection on mac. After that you can find following log.
   
   ``` sh
   failed to receive:
   file:../kii/kii/kii_push.c, line:431 kii-error: mqtt receive data error
   file:../kii/kii/kii_mqtt.c, line:54 closing socket as socket is already created.
   failed to get host.
   file:../kii/kii/kii_mqtt.c, line:63 connecting socket is failed.
   file:../kii/kii/kii_push.c, line:500 kii-error: mqtt connect error
   ```
   
   This log indicates network connection is closed. I also found `fail to get host` message which you described in this log. 
   
   After seeing above log, following logs is repeatedly appeared in terminal.
   
   ``` sh
   file:../kii/kii-core/kii_core.c, line:466 request: POST https://api-jp.kii.com/api/apps/60db8b09/installations HTTP/1.1
   host:api-jp.kii.com
   x-kii-appid:60db8b09
   x-kii-appkey:0afb6d37129b66b0c0b663232300c1da
   x-kii-sdk:sn=tic;sv=0.9.1
   content-type:application/vnd.kii.InstallationCreationRequest+json
   authorization:bearer 3t2-LfDz5pDvIXOnuPQR_b9PgOvCCjBNOXhvTZ_6MYI
   content-length:47
   
   {"installationType":"MQTT","development":false}
   file:../kii/kii-core/kii_core.c, line:147 socket state: 0
   file:../kii/kii-core/kii_core.c, line:147 socket state: 1
   failed to get host.
   file:../kii/kii-core/kii_core.c, line:481 fail to send request
   file:../kii/kii/kii_push.c, line:460 kii-error: mqtt installation error
   ```
5. Reconnect network connection
   
   To reconnect network connection, I turned on Wi-Fi connection on mac. After that you can find following log.
   
   ``` sh
   file:../kii/kii/kii_push.c, line:338 readPointer: 1566747936
   ```
   
   This log indicates test application successfully reconnect to network.

According to above procedures and results, I think recovering network is fine.
Could you give me more detail condition?

**Comment by dairyo** [comment]
@kiiCarlos said currently it does not happen. So I stop to check this issue.

carlos's comment:

```
@shinsuke.nara @satoshi - Thanks for checking.  It didn’t happen over night this time.  I’ll kept it running and let you know if it happens again.
```

**Comment by dairyo** [comment]
@kiiCarlos said:

```
This time I got the error failed to receive,  
I found that they are being triggered in the kii_core_secure_socket.c. 
Is there a quick way or a higher level c file where I can tell it 
to reset or retry the connection?
```

The triggered position which carlos pointed out is https://github.com/KiiPlatform/KiiThingSDK-Embedded/blob/d095a861fa3325cd662cc5b9ff7254f3bad98208/kii-core/linux/kii_core_secure_socket.c#L135 

I assumes that thing-if SDK automatically recover network connection. 
I want to know more detail condition.
Could you retrieve SDK execution log? I  want to investigate the SDK execution log.

You can get the log with an application compiled with following command:

``` sh
make DEBUG=1
```

**Comment by kiiCarlos** [comment]
Attached is my runtime log.  Is this what you needed?
[run.log.zip](https://github.com/KiiPlatform/thing-if-ThingSDK/files/485318/run.log.zip)

**Comment by naoki-akimoto** [comment]
I think, this happened when prv_update_status (in kii_thing_if.c) stopped.

In this case, two or more tasks (prv_update_status and others) run on background.
When other task was stoppped by network error, re-run.
But when prv_update_status was stoppped, no retry.

**Comment by satoshikumano** [comment]
fixed.
